### 데이터 간의 유사성을 판단하기 위해서는, 거리를 계산합니다.

주로 사용하는 거리 함수(distance function, metric)로는 다음 3가지가 있습니다.


1. Manhattan Distance (L1 distance)

2. Euclidean Distance (L2 distance)

3. Cosine Distance


위의 3가지 metric을 직접 구현해보고 차이점을 확인해봅니다.

In [28]:
import numpy as np


v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

v3 = np.array([3, 1, 2])
v4 = np.array([3, -1, -1])

In [33]:
def manhattan_distance(x, y):

    """
    x, y : np.array
    return : x와 y 사이의 manhattan_distance
    """
    
    return np.sum(np.abs(x - y))

In [32]:
np.sum(np.abs(v1 - v2))

2

In [34]:
manhattan_distance(v1, v2)

2

In [35]:
def euclidean_distance(x, y):
    """
    x, y : np.array
    return : x와 y 사이의 euclidean_distance
    """
    
    
    
    return ((x - y) ** 2).sum() ** 0.5

In [36]:
((v1 - v2) ** 2).sum() ** 0.5

1.4142135623730951

In [37]:
euclidean_distance(v1, v2)

1.4142135623730951

In [38]:
def cosine_distance(x, y):

    """
    x, y : np.array
    return : x와 y 사이의 cosine_distance
    """
    dot = x @ y #(x * y) // np.dot(x, y)
    norm_x = np.sqrt(np.sum(np.square(x)))
#     norm_x = euclidean_distance(x, np.zeros(len(x))) 
    norm_y = np.sqrt(np.sum(np.square(y)))
    norm = norm_x * norm_y
    
    
    cosine_similarity = dot / norm
    
    
    return 1 - cosine_similarity

In [39]:
cosine_distance(v1, v2)

1.0

In [40]:
manhattan_distance(v1, v2), euclidean_distance(v1, v2), cosine_distance(v1, v2)

(2, 1.4142135623730951, 1.0)

In [41]:
manhattan_distance(v3, v4), euclidean_distance(v3, v4), cosine_distance(v3, v4)

(5, 3.605551275463989, 0.5165062215847718)

### 가장 유사한 고객 찾기!

In [44]:
import pandas as pd

data = pd.read_csv('./train.csv')
data

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
0,2,1,D3,10,0.076923,2,1,1,0.641791,0.581818,...,0,0,0,0,0,0,0,0,0,8
1,5,1,A1,26,0.076923,2,3,1,0.059701,0.600000,...,0,0,0,0,0,0,0,0,0,4
2,6,1,E1,26,0.076923,2,3,1,0.029851,0.745455,...,0,0,0,0,0,0,0,0,0,8
3,7,1,D4,10,0.487179,2,3,1,0.164179,0.672727,...,0,0,0,0,0,0,0,0,0,8
4,8,1,D2,26,0.230769,2,3,1,0.417910,0.654545,...,0,0,0,0,0,0,0,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59376,79142,1,D1,10,0.230769,2,3,1,0.074627,0.709091,...,0,0,0,0,0,0,0,0,0,4
59377,79143,1,D3,26,0.230769,2,3,1,0.432836,0.800000,...,0,0,0,0,0,0,0,0,0,7
59378,79144,1,E1,26,0.076923,2,3,1,0.104478,0.745455,...,0,0,0,0,0,0,0,0,0,8
59379,79145,1,D2,10,0.230769,2,3,1,0.507463,0.690909,...,1,0,0,0,0,0,0,0,0,8
59380,79146,1,A8,26,0.076923,2,3,1,0.447761,0.781818,...,0,0,0,0,0,0,0,0,0,7

In [46]:
## 6번 고객과 가장 가까운 고객 id 찾기

data = data.iloc[:, :15]
data

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,BMI,Employment_Info_1,Employment_Info_2,Employment_Info_3
0,2,1,D3,10,0.076923,2,1,1,0.641791,0.581818,0.148536,0.323008,0.028,12,1
1,5,1,A1,26,0.076923,2,3,1,0.059701,0.600000,0.131799,0.272288,0.000,1,3
2,6,1,E1,26,0.076923,2,3,1,0.029851,0.745455,0.288703,0.428780,0.030,9,1
3,7,1,D4,10,0.487179,2,3,1,0.164179,0.672727,0.205021,0.352438,0.042,9,1
4,8,1,D2,26,0.230769,2,3,1,0.417910,0.654545,0.234310,0.424046,0.027,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59376,79142,1,D1,10,0.230769,2,3,1,0.074627,0.709091,0.320084,0.519103,0.020,1,3
59377,79143,1,D3,26,0.230769,2,3,1,0.432836,0.800000,0.403766,0.551119,0.100,9,1
59378,79144,1,E1,26,0.076923,2,3,1,0.104478,0.745455,0.246862,0.360969,0.035,9,1
59379,79145,1,D2,10,0.230769,2,3,1,0.507463,0.690909,0.276151,0.462452,0.038,9,1
59380,79146,1,A8,26,0.076923,2,3,1,0.447761,0.781818,0.382845,0.539563,0.123,9,1

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59381 entries, 0 to 59380
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 59381 non-null  int64
 1   Product_Info_1     59381 non-null  int64
 2   Product_Info_2     59381 non-null  object
 3   Product_Info_3     59381 non-null  int64
 4   Product_Info_4     59381 non-null  float64
 5   Product_Info_5     59381 non-null  int64
 6   Product_Info_6     59381 non-null  int64
 7   Product_Info_7     59381 non-null  int64
 8   Ins_Age            59381 non-null  float64
 9   Ht                 59381 non-null  float64
 10  Wt                 59381 non-null  float64
 11  BMI                59381 non-null  float64
 12  Employment_Info_1  59362 non-null  float64
 13  Employment_Info_2  59381 non-null  int64
 14  Employment_Info_3  59381 non-null  int64
dtypes: float64(6), int64(8), object(1)
memory usage: 6.8+ MB

In [48]:
data.isnull().sum()

Id                    0
Product_Info_1        0
Product_Info_2        0
Product_Info_3        0
Product_Info_4        0
Product_Info_5        0
Product_Info_6        0
Product_Info_7        0
Ins_Age               0
Ht                    0
Wt                    0
BMI                   0
Employment_Info_1    19
Employment_Info_2     0
Employment_Info_3     0
dtype: int64

In [50]:
data = data.drop(columns=["Product_Info_2", "Employment_Info_1"])
data

,Id,Product_Info_1,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,BMI,Employment_Info_2,Employment_Info_3
0,2,1,10,0.076923,2,1,1,0.641791,0.581818,0.148536,0.323008,12,1
1,5,1,26,0.076923,2,3,1,0.059701,0.600000,0.131799,0.272288,1,3
2,6,1,26,0.076923,2,3,1,0.029851,0.745455,0.288703,0.428780,9,1
3,7,1,10,0.487179,2,3,1,0.164179,0.672727,0.205021,0.352438,9,1
4,8,1,26,0.230769,2,3,1,0.417910,0.654545,0.234310,0.424046,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59376,79142,1,10,0.230769,2,3,1,0.074627,0.709091,0.320084,0.519103,1,3
59377,79143,1,26,0.230769,2,3,1,0.432836,0.800000,0.403766,0.551119,9,1
59378,79144,1,26,0.076923,2,3,1,0.104478,0.745455,0.246862,0.360969,9,1
59379,79145,1,10,0.230769,2,3,1,0.507463,0.690909,0.276151,0.462452,9,1
59380,79146,1,26,0.076923,2,3,1,0.447761,0.781818,0.382845,0.539563,9,1

In [51]:
ids = data['Id']
data = data.drop(columns='Id')
data

,Product_Info_1,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,Wt,BMI,Employment_Info_2,Employment_Info_3
0,1,10,0.076923,2,1,1,0.641791,0.581818,0.148536,0.323008,12,1
1,1,26,0.076923,2,3,1,0.059701,0.600000,0.131799,0.272288,1,3
2,1,26,0.076923,2,3,1,0.029851,0.745455,0.288703,0.428780,9,1
3,1,10,0.487179,2,3,1,0.164179,0.672727,0.205021,0.352438,9,1
4,1,26,0.230769,2,3,1,0.417910,0.654545,0.234310,0.424046,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...
59376,1,10,0.230769,2,3,1,0.074627,0.709091,0.320084,0.519103,1,3
59377,1,26,0.230769,2,3,1,0.432836,0.800000,0.403766,0.551119,9,1
59378,1,26,0.076923,2,3,1,0.104478,0.745455,0.246862,0.360969,9,1
59379,1,10,0.230769,2,3,1,0.507463,0.690909,0.276151,0.462452,9,1
59380,1,26,0.076923,2,3,1,0.447761,0.781818,0.382845,0.539563,9,1

In [53]:
## TO-DO: 6번 고객과 가장 가까운 고객을 euclidean_distance 기준으로 찾기!

target_user = data.iloc[2]
target_user

Product_Info_1        1.000000
Product_Info_3       26.000000
Product_Info_4        0.076923
Product_Info_5        2.000000
Product_Info_6        3.000000
Product_Info_7        1.000000
Ins_Age               0.029851
Ht                    0.745455
Wt                    0.288703
BMI                   0.428780
Employment_Info_2     9.000000
Employment_Info_3     1.000000
Name: 2, dtype: float64

In [67]:
## 최소값 찾는 방법
#tip 처음에 최대를 설정해둔다 ex)123456789

min_idx = 0
min_distance = 123456789
for i in data.index:
    if i == 2:
        continue
    distance = euclidean_distance(target_user, data.iloc[i])
    if distance < min_distance:
        min_distance = distance
        min_idx = i
print("user_ID :", ids[min_idx])

user_ID : 24878